// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuViZCkNkAeRoufvzc7JL0Bb5xtfrmnno',
    appId: '1:171344911356:web:10045683c3374dc1ecf079',
    messagingSenderId: '171344911356',
    projectId: 'chat-flutter-38d2e',
    authDomain: 'chat-flutter-38d2e.firebaseapp.com',
    storageBucket: 'chat-flutter-38d2e.appspot.com',
    measurementId: 'G-74MLWVH5ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZaWK4_Nep13GJ9UO8go1W_Vn0EHPhyKI',
    appId: '1:171344911356:android:004705b0e749dc9decf079',
    messagingSenderId: '171344911356',
    projectId: 'chat-flutter-38d2e',
    storageBucket: 'chat-flutter-38d2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZr_RFEPJlOceorwB_-KpImK8X67IhSzE',
    appId: '1:171344911356:ios:7e492d592268297cecf079',
    messagingSenderId: '171344911356',
    projectId: 'chat-flutter-38d2e',
    storageBucket: 'chat-flutter-38d2e.appspot.com',
    iosClientId: '171344911356-6afksid6jjv75e12tq16815kk4jfgam7.apps.googleusercontent.com',
    iosBundleId: 'com.reyfernando6.flutterChat',
  );
}
